const express = require('express');
const router = express.Router();
const { getDepartments, createDepartment, updateDepartment, deleteDepartment, getDepartmentEmployees } = require('../controllers/departmentController');
const { protect, authorize } = require('../middleware/auth');
router.get('/', protect, getDepartments);
router.get('/:id/employees', protect, getDepartmentEmployees);
router.post('/', protect, authorize('admin', 'hr_manager'), createDepartment);
router.put('/:id', protect, authorize('admin', 'hr_manager'), updateDepartment);
router.delete('/:id', protect, authorize('admin', 'hr_manager'), deleteDepartment);
module.exports = router;
